### ISSUE TITLE
Looking for vulnerabilities

### ISSUE THREAD

**Issue by Aarui920511** [Whitecat18/Javahexor#1]
Can this tool be applied to bug bounties? How to use it?

**Comment by Whitecat18** [comment]
Nope. This is an Social Enginerr Tool used to trick People to Enter into their custom Sites that is used to gather IP's, Some System browser Information such as the browser he is using, screen widhh and height and mainly we can get their live location and send it out Telegram Bot ..!

For More Information . Please Read the <a href="https://github.com/Whitecat18/Javahexor?tab=readme-ov-file#javahexor-" > README.md </a>

Thank You .
